-- Name: Erin Ledford 
-- EMAIL: eledford@unomaha.edu
-- Class: BIOI 4870/CSCI 8876, Spring 2021 
-- Assignment #: Final Project
-- 
-- Honor Pledge: On my honor as a student of the University of Nebraska at 
-- Omaha, I have neither given nor received unauthorized help on 
-- this programming assignment.
-- 
-- Partners: List the full names and e-mail addresses of everyone you may have 
-- discussed the program with or worked on the program with. It is not necessary 
-- to list your instructor. If none, state "NONE". NONE
-- 
-- Sources: List all the sources you may have used for this assignment. It is 
-- not necessary to list course content or manual pages, just internet 
-- resources you looked up. If none, state "NONE." NCBI, Ensembl, Uniprot
-- NCBI: https://www.ncbi.nlm.nih.gov/gene/4519, https://www.ncbi.nlm.nih.gov/gene/?term=4541, https://www.ncbi.nlm.nih.gov/gene/?term=4538,
-- https://www.ncbi.nlm.nih.gov/gene/?term=4539%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4537%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4509%5Buid%5D,
-- https://www.ncbi.nlm.nih.gov/gene/?term=4514%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4508%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4513%5Buid%5D,
-- https://www.ncbi.nlm.nih.gov/gene/?term=4512%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4536%5Buid%5D, https://www.ncbi.nlm.nih.gov/gene/?term=4535%5Buid%5D,
-- https://www.ncbi.nlm.nih.gov/gene/?term=4540%5Buid%5D
-- Uniprot: https://www.uniprot.org/uniprot/P00156, https://www.uniprot.org/uniprot/P03923, https://www.uniprot.org/uniprot/P03905,
-- https://www.uniprot.org/uniprot/P03901, https://www.uniprot.org/uniprot/P03897, https://www.uniprot.org/uniprot/P00414,
-- https://www.uniprot.org/uniprot/P00846, https://www.uniprot.org/uniprot/P03928, https://www.uniprot.org/uniprot/P00403,
-- https://www.uniprot.org/uniprot/P00395, https://www.uniprot.org/uniprot/P03891, https://www.uniprot.org/uniprot/P03886,
-- https://www.uniprot.org/uniprot/P03915
-- Ensembl: https://uswest.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000198886;r=MT:10760-12137;t=ENST00000361381, https://uswest.ensembl.org/Homo_sapiens/Gene/Phenotype?db=core;g=ENSG00000198727;r=MT:14747-15887;t=ENST00000361789,
-- https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198695;r=MT:14149-14673;t=ENST00000361681, https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198840;r=MT:10059-10404;t=ENST00000361227,
-- https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000212907;r=MT:10470-10766;t=ENST00000361335, https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198938;r=MT:9207-9990;t=ENST00000362079,
-- https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198899;r=MT:8527-9207;t=ENST00000361899, https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198712;r=MT:7586-8269;t=ENST00000361739,
-- https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198804;r=MT:5904-7445;t=ENST00000361624, https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198763;r=MT:4470-5511;t=ENST00000361453,
-- https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198888;r=MT:3307-4262;t=ENST00000361390, https://uswest.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000198786;r=MT:12337-14148;t=ENST00000361567

-- MIT License

--Copyright (c) [2020] [Erin Ledford]

--Permission is hereby granted, free of charge, to any person obtaining a copy
--of this software and associated documentation files (the "Software"), to deal
--in the Software without restriction, including without limitation the rights
--to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
--copies of the Software, and to permit persons to whom the Software is
--furnished to do so, subject to the following conditions:

--The above copyright notice and this permission notice shall be included in all
--copies or substantial portions of the Software.

--THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
--IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
--FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
--AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
--LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
--OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
--SOFTWARE.

USE eledford;

--Drops genes and proteins if they already exist in the database
DROP TABLE IF EXISTS genes;

DROP TABLE IF EXISTS proteins;

--The DDL to create tables for genes and proteins
-- Data from NCBI: accession_number_gene, gene_symbol, full_name, organism, last_updated, location, bp_length, gene_type
-- and sequence for the genes table
-- Data from Ensembl: num_associated variants, num_highest_variant, highest_disease_variant for genes table
-- Data from Uniprot: associated_protein for the genes table
CREATE TABLE genes (
	accession_number_gene varchar(100),
	gene_symbol varchar(100),
	full_name varchar(1000),
	associated_protein varchar(100),
	organism varchar(100),
	last_updated varchar(100),
	location varchar(100),
	bp_length varchar(100),
	gene_type varchar(100), 
	sequence varchar(3000),
	num_associated_variants int,
	num_highest_variant varchar(100),
	highest_disease_variant varchar(100),
	PRIMARY KEY (accession_number_gene)
);

-- Data from Uniprot: accession_number_prot, full_name, associated_geneSymbol, organism, last_updated, location, aa_length,
-- and sequence for the proteins table
CREATE TABLE proteins (
	accession_number_prot varchar(100),
	full_name varchar(100),
	associated_geneSymbol varchar(100),
	organism varchar(100),
	last_updated varchar(100),
	location varchar(1500),
	aa_length varchar(100),
	sequence varchar(1000),
	PRIMARY KEY (accession_number_prot)
);

-- The DML inserted into the tables

INSERT INTO genes VALUES (
	"4519",
	"MT-CYB",
	"mitochondrially encoded cytochrome b",
	"P00156",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (14747..15887)",
	"1141 bp",
	"protein coding",
	concat(">NC_012920.1:14747-15887 Homo sapiens mitochondrion, complete genome
		",
	"ATGACCCCAATACGCAAAACTAACCCCCTAATAAAATTAATTAACCACTCATTCATCGACCTCCCCACCC
CATCCAACATCTCCGCATGATGAAACTTCGGCTCACTCCTTGGCGCCTGCCTGATCCTCCAAATCACCAC
AGGACTATTCCTAGCCATGCACTACTCACCAGACGCCTCAACCGCCTTTTCATCAATCGCCCACATCACT
CGAGACGTAAATTATGGCTGAATCATCCGCTACCTTCACGCCAATGGCGCCTCAATATTCTTTATCTGCC
TCTTCCTACACATCGGGCGAGGCCTATATTACGGATCATTTCTCTACTCAGAAACCTGAAACATCGGCAT
TATCCTCCTGCTTGCAACTATAGCAACAGCCTTCATAGGCTATGTCCTCCCGTGAGGCCAAATATCATTC
TGAGGGGCCACAGTAATTACAAACTTACTATCCGCCATCCCATACATTGGGACAGACCTAGTTCAATGAA
TCTGAGGAGGCTACTCAGTAGACAGTCCCACCCTCACACGATTCTTTACCTTTCACTTCATCTTGCCCTT
CATTATTGCAGCCCTAGCAACACTCCACCTCCTATTCTTGCACGAAACGGGATCAAACAACCCCCTAGGA
ATCACCTCCCATTCCGATAAAATCACCTTCCACCCTTACTACACAATCAAAGACGCCCTCGGCTTACTTC
TCTTCCTTCTCTCCTTAATGACATTAACACTATTCTCACCAGACCTCCTAGGCGACCCAGACAATTATAC
CCTAGCCAACCCCTTAAACACCCCTCCCCACATCAAGCCCGAATGATATTTCCTATTCGCCTACACAATT
CTCCGATCCGTCCCTAACAAACTAGGAGGCGTCCTTGCCCTATTACTATCCATCCTCATCCTAGCAATAA
TCCCCATCCTCCATATATCCAAACAACAAAGCATAATATTTCGCCCACTAAGCCAATCACTTTATTGACT
CCTAGCCGCAGACCTCCTCATTCTAACCTGAATCGGAGGACAACCAGTAAGCTACCCTTTTACCATCATT
GGACAAGTAGCATCCGTACTATACTTCACAACAATCCTAATCCTAATACCAACTATCTCCCTAATTGAAA
ACAAAATACTCAAATGGGCCT"),
	"298",
	"240",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4541",
	"MT-ND6",
	"mitochondrially encoded NADH dehydrogenase 6",
	"P03923",
	"Homo sapiens (Human)",
	"16-Mar-2021",
	"NC_012920.1 (14149..14673, complement)",
	"525 bp",
	"protein coding",
	concat(">NC_012920.1:c14673-14149 Homo sapiens mitochondrion, complete genome
		", 
		"ATGATGTATGCTTTGTTTCTGTTGAGTGTGGGTTTAGTAATGGGGTTTGT",
		"GGGGTTTTCTTCTAAGCCTTCTCCTATTTATGGGGGTTTAGTATTGATTGTTAGCGGT",
		"GTGGTCGGGTGTGTTATTATTCTGAATTTTGGGGGAGGTTATATGGGTTTAATAGTTTTT",
		"TTAATTTATTTAGGGGGAATGATGGTTGTCTTTGGATATACTACAGCGATGGCTATTGAGGA",
		"GTATCCTGAGGCATGGGGGTCAGGGGTTGAGGTCTTGGTGAGTGTTTTAGTGGGGTTAGCGAT",
		"GGAGGTAGGATTGGTGCTGTGGGTGAAAGAGTATGATGGGGTGGTGGTTGTGGTAAACTTTAAT",
		"AGTGTAGGAAGCTGAATAATTTATGAAGGAGAGGGGTCAGGGTTGATTCGGGAGGATCCTATTGGT",
		"GCGGGGGCTTTGTATGATTATGGGCGTTGATTAGTAGTAGTTACTGGTTGAACATTGTTTGTTGGTG",
		"TATATATTGTAATTGAGATTGCTCGGGGGAATAGG"),
	"96",
	"83",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4538",
	"MT-ND4",
	"mitochondrially encoded NADH dehydrogenase 4",
	"P03905",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (10760..12137)",
	"1378 bp",
	"protein coding",
	concat(">NC_012920.1:10760-12137 Homo sapiens mitochondrion, complete genome
		", "ATGCTAAAACTAATCGTCCCAACAATTATATTACTACCACTGACATGACTTTCCAAAAAACACATAATTTGAATCAACACAACCACCCACAGCCTAATTATTAGCATCATCCCTCTACTATTTTTTAACCAAATCAACAA
CAACCTATTTAGCTGTTCCCCAACCTTTTCCTCCGACCCCCTAACAACCCCCCTCCTAATACTAACTACCTGACTCCTACCCCTCACAATCATGGCAAGCCAACGCCACTTATCCAGTGAACCACTATCACGAAAAAAACTCTACCTCTCTATACTAATCTCCCTACAAATCTCCTTAATTATAACATTCACAGCCACAGAACTAATCATATTTTATATCTTCTTCGAAACCACACTTATCCCCACCTTGGCTATCATCACCCGATGAGGCAACCAGCCAGAACGCCTGAACGCAGGCACATACTTCCTATTCTACACCCTAGTAGGCTCCCTTCCCCTACTCATCGCACTAATTTACACTCACAACACCCTAGGCTCACTAAACATTCTACTACTCACTCTCACTGCCCAAGAACTATCAAACTCCTGAGCCAACAACTTAATATGACTAGCTTACACAATAGCTTTTATAGTAAAGATACCTCTTTACGGACTCCACTTATGACTCCCTAAAGCCCATGTCGAAGCCCCCATCGCTGGGTCAATAGTACTTGCCGCAG
TACTCTTAAAACTAGGCGGCTATGGTATAATACGCCTCACACTCATTCTCAACCCCCTGACAAAACACATAGCCTACCCCTTCCTTGTACTATCCCTATGAGGCATAATTATAACAAGCTCCATCTGCCTACGACAAACAGACCTAAAATCGCTCATTGCATACTCTTCAATCAGCCACATAGCCCTCGTAGTAACAGCCATTCTCATCCAAACCCCCTGAAGCTTCACCGGCGCAGTCATTCTCATAATCGCCCACGGGCTTACATCCTCATTACTATTCTGCCTAGCAAACTCAAACTACGAACGCACTCACAGTCGCATCATAATCCTCTCTCAAGGACTTCAAACTCTACTCCCACTAATAGCTTTTTGATGACTTCTAGCAAGCCTCGCTAACCTCGCCTTACCCCCCACTATTAACCTACTGGGAGAACTCTCTGTGCTAGTAACCACGTTCTCCTGATCAAATATCACTCTCCTACTTACAGGACTCAACATACTAGTCACAGCCCTATACTCCCTCTACATATTTACCACAACACAATGGGGCTCACTCACC
CACCACATTAACAACATAAAACCCTCATTCACACGAGAAAACACCCTCATGTTCATACACCTATCCCCCATTCTCCTCCTATCCCTCAACCCCGACATCATTACCGGGTTTTCCTCTT"),
	"126",
	"112",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4539",
	"MT-ND4L",
	"mitochondrially encoded NADH 4L dehydrogenase",
	"P03901",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (10470..10766)",
	"297 bp",
	"protein coding",
	concat(">NC_012920.1:10470-10766 Homo sapiens mitochondrion, complete genome
		",
"ATGCCCCTCATTTACATAAATATTATACTAGCATTTACCATCTCACTTCTAGGAATACTAGTATATCGCTCACACCTCATATCCTCCCTACTATGCCTAGAAGGAATAATACTATCGCTGTTCATTATAGCTACTCTCATAACCCTCAACACCCACTCCCTCTTAGCCAATATTGTGCCTATTGCCATACTAGTCTTTGCCGCCTGCGAAGCAGCGGTGGGCCTAGCCCTACTAGTCTCAATCTCCAACACATATGGCCTAGACTACGTACATAACCTAAACCTACTCCAATGCTAA"),
	"29",
	"25",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4537",
	"MT-ND3",
	"mitochondrially encoded NADH dehydrogenase 3",
	"P03897",
	"Homo sapiens (human)",
	"2-Mar-2021",
	"NC_012920.1 (10059..10404)",
	"346 bp",
	"protein coding",
	concat(">NC_012920.1:10059-10404 Homo sapiens mitochondrion, complete genome
		","ATAAACTTCGCCTTAATTTTAATAATCAACACCCTCCTAGCCTTACTACTAATAATTATTACATTTTGACTACCACAACTCAACGGCTACATAGAAAAATCCACCCCTTACGAGTGCGGCTTCGACCCTATATCCCCCGCCCGCGTCCCTTTCTCCATAAAATTCTTCTTAGTAGCTATTACCTTCTTATTATTTGATCTAGAAATTGCCCTCCTTTTACCCCTACCATGAGCCCTACAAACAACTAACCTGCCACTAATAGTTATGTCATCCCTCTTATTAATCATCATCCTAGCCCTAAGTCTGGCCTATGAGTGACTACAAAAAGGATTAGACTGAACCGAAT"),
	"38",
	"37",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4514",
	"MT-CO3",
	"mitochondrially encoded cytochrome c oxidase III",
	"P0414",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (9207..9990)",
	"784 bp",
	"protein coding",
	concat(">NC_012920.1:9207-9990 Homo sapiens mitochondrion, complete genome
		","ATGACCCACCAATCACATGCCTATCATATAGTAAAACCCAGCCCATGACCCCTAACAGGGGCCCTCTCAGCCCTCCTAATGACCTCCGGCCTAGCCATGTGATTTCACTTCCACTCCATAACGCTCCTCATACTAGGCCTACTAACCAACACACTAACCATATACCAATGATGGCGCGATGTAACACGAGAAAGCACATACCAAGGCCACCACACACCACCTGTCCAAAAAGGCCTTCGATACGGGATAATCCTATTTATTACCTCAGAAGTTTTTTTCTTCGCAGGATTTTTCTGAGCCTTTTACCACTCCAGCCTAGCCCCTACCCCCCAATTAGGAGGGCACTGGCCCCCAACAGGCATCACCCCGCTAAATCCCCTAGAAGTCCCACTCCTAAACACATCCGTATTACTCGCATCAGGAGTATCAATCACCTGAGCTCACCATAGTCTAATAGAAAACAACCGAAACCAAATAATTCAAGCACTGCTTATTACAATTTTACTGGGTCTCTATTTTACCCTCCTACAAGCCTCAGAGTACTTCGAGTCTCCCTTCACCATTTCCGACGGCATCTACGGCTCAACATTTTTTGTAGCCACAGGCTTCCACGGACTTCACGTCATTATTGGCTCAACTTTCCTCACTATCTGCTTCATCCGCCAACTAATATTTCACTTTACATCCAAACATCACTTTGGCTTCGAAGCCGCCGCCTGATACTGGCATTTTGTAGATGTGGTTTGACTATTTCTGTATGTCTCCATCTATTGATGAGGGTCTT"),
	"151",
	"131",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4508",
	"MT-ATP6",
	"mitochondrially encoded ATP synthase 6",
	"P00846",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (8527..9207)",
	"681 bp",
	"protein coding",
	concat(">NC_012920.1:8527-9207 Homo sapiens mitochondrion, complete genome
		","ATGAACGAAAATCTGTTCGCTTCATTCATTGCCCCCACAATCCTAGGCCTACCCGCCGCAGTACTGATCATTCTATTTCCCCCTCTATTGATCCCCACCTCCAAATATCTCATCAACAACCGACTAATCACCACCCAACAATGACTAATCAAACTAACCTCAAAACAAATGATAACCATACACAACACTAAAGGACGAACCTGATCTCTTATACTAGTATCCTTAATCATTTTTATTGCCACAACTAACCTCCTCGGACTCCTGCCTCACTCATTTACACCAACCACCCAACTATCTATAAACCTAGCCATGGCCATCCCCTTATGAGCGGGCACAGTGATTATAGGCTTTCGCTCTAAGATTAAAAATGCCCTAGCCCACTTCTTACCACAAGGCACACCTACACCCCTTATCCCCATACTAGTTATTATCGAAACCATCAGCCTACTCATTCAACCAATAGCCCTGGCCGTACGCCTAACCGCTAACATTACTGCAGGCCACCTACTCATGCACCTAATTGGAAGCGCCACCCTAGCAATATCAACCATTAACCTTCCCTCTACACTTATCATCTTCACAATTCTAATTCTACTGACTATCCTAGAAATCGCTGTCGCCTTAATCCAAGCCTACGTTTTCACACTTCTAGTAAGCCTCTACCTGCACGACAACACATAA"),
	"266",
	"244",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4509",
	"MT-ATP8",
	"mitochondrially encoded ATP synthase 8",
	"P03928",
	"Homo sapiens (human)",
	"17-Apr-2021",
	"NC_012920.1 (8366..8572)",
	"207 bp",
	"protein coding",
	concat(">NC_012920.1:8366-8572 Homo sapiens mitochondrion, complete genome
		","ATGCCCCAACTAAATACTACCGTATGGCCCACCATAATTACCCCCATACTCCTTACACTATTCCTCATCACCCAACTAAAAATATTAAACACAAACTACCACCTACCTCCCTCACCAAAGCCCATAAAAATAAAAAATTATAACAAACCCTGAGAACCAAAATGAACGAAAATCTGTTCGCTTCATTCATTGCCCCCACAATCCTAG"),
	"84",
	"75",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4513",
	"MT-CO2",
	"mitochondrially encoded cytochrome c oxidase II",
	"P00403",
	"Homo sapiens (human)",
	"7-Apr-2021",
	"NC_012920.1 (7586..8269)",
	"684 bp",
	"protein coding",
	concat(">NC_012920.1:7586-8269 Homo sapiens mitochondrion, complete genome
		", "ATGGCACATGCAGCGCAAGTAGGTCTACAAGACGCTACTTCCCCTATCATAGAAGAGCTTATCACCTTTCATGATCACGCCCTCATAATCATTTTCCTTATCTGCTTCCTAGTCCTGTATGCCCTTTTCCTAACACTCACAACAAAACTAACTAATACTAACATCTCAGACGCTCAGGAAATAGAAACCGTCTGAACTATCCTGCCCGCCATCATCCTAGTCCTCATCGCCCTCCCATCCCTACGCATCCTTTACATAACAGACGAGGTCAACGATCCCTCCCTTACCATCAAATCAATTGGCCACCAATGGTACTGAACCTACGAGTACACCGACTACGGCGGACTAATCTTCAACTCCTACATACTTCCCCCATTATTCCTAGAACCAGGCGACCTGCGACTCCTTGACGTTGACAATCGAGTAGTACTCCCGATTGAAGCCCCCATTCGTATAATAATTACATCACAAGACGTCTTGCACTCATGAGCTGTCCCCACATTAGGCTTAAAAACAGATGCAATTCCCGGACGTCTAAACCAAACCACTTTCACCGCTACACGACCGGGGGTATACTACGGTCAATGCTCTGAAATCTGTGGAGCAAACCACAGTTTCATGCCCATCGTCCTAGAATTAATTCCCCTAAAAATCTTTGAAATAGGGCCCGTATTTACCCTATAG"),
	"113",
	"84",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4512",
	"MT-CO1",
	"mitochondrially encoded cytochrome c oxidase I",
	"P00395",
	"Homo sapiens (human)",
	"7-Apr-2021",
	"NC_012920.1 (5904..7445)",
	"1542 bp",
	"protein coding",
	concat(">NC_012920.1:5904-7445 Homo sapiens mitochondrion, complete genome
		","ATGTTCGCCGACCGTTGACTATTCTCTACAAACCACAAAGACATTGGAACACTATACCTATTATTCGGCGCATGAGCTGGAGTCCTAGGCACAGCTCTAAGCCTCCTTATTCGAGCCGAGCTGGGCCAGCCAGGCAACCTTCTAGGTAACGACCACATCTACAACGTTATCGTCACAGCCCATGCATTTGTAATAATCTTCTTCATAGTAATACCCATCATAATCGGAGGCTTTGGCAACTGACTAGTTCCCCTAATAATCGGTGCCCCCGATATGGCGTTTCCCCGCATAAACAACATAAGCTTCTGACTCTTACCTCCCTCTCTCCTACTCCTGCTCGCATCTGCTATAGTGGAGGCCGGAGCAGGAACAGGTTGAACAGTCTACCCTCCCTTAGCAGGGAACTACTCCCACCCTGGAGCCTCCGTAGACCTAACCATCTTCTCCTTACACCTAGCAGGTGTCTCCTCTATCTTAGGGGCCATCAATTTCATCACAACAATTATCAATATAAAACCCCCTGCCATAACCCAATACCAAACGCCCCTCTTCGTCTGATCCGTCCTAATCACAGCAGTCCTACTTCTCCTATCTCTCCCAGTCCTAGCTGCTGGCATCACTATACTACTAACAGACCGCAACCTCAACACCACCTTCTTCGACCCCGCCGGAGGAGGAGACCCCATTCTATACCAACACCTATTCTGATTTTTCGGTCACCCTGAAGTTTATATTCTTATCCTACCAGGCTTCGGAATAATCTCCCATATTGTAACTTACTACTCCGGAAAAAAAGAACCATTTGGATACATAGGTATGGTCTGAGCTATGATATCAATTGGCTTCCTAGGGTTTATCGTGTGAGCACACCATATATTTACAGTAGGAATAGACGTAGACACACGAGCATATTTCACCTCCGCTACCATAATCATCGCTATCCCCACCGGCGTCAAAGTATTTAGCTGACTCGCCACACTCCACGGAAGCAATATGAAATGATCTGCTGCAGTGCTCTGAGCCCTAGGATTCATCTTTCTTTTCACCGTAGGTGGCCTGACTGGCATTGTATTAGCAAACTCATCACTAGACATCGTACTACACGACACGTACTACGTTGTAGCCCACTTCCACTATGTCCTATCAATAGGAGCTGTATTTGCCATCATAGGAGGCTTCATTCACTGATTTCCCCTATTCTCAGGCTACACCCTAGACCAAACCTACGCCAAAATCCATTTCACTATCATATTCATCGGCGTAAATCTAACTTTCTTCCCACAACACTTTCTCGGCCTATCCGGAATGCCCCGACGTTACTCGGACTACCCCGATGCATACACCACATGAAACATCCTATCATCTGTAGGCTCATTCATTTCTCTAACAGCAGTAATATTAATAATTTTCATGATTTGAGAAGCCTTCGCTTCGAAGCGAAAAGTCCTAATAGTAGAAGAACCCTCCATAAACCTGGAGTGACTATATGGATGCCCCCCACCCTACCACACATTCGAAGAACCCGTATACATAAAATCTAGA"),
	"205",
	"149",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4536",
	"MT-ND2",
	"mitochondrially encoded NADH dehydrogenase 2",
	"P03891",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (4470..5511)",
	"1042 bp",
	"protein coding",
	concat(">NC_012920.1:4470-5511 Homo sapiens mitochondrion, complete genome
		","ATTAATCCCCTGGCCCAACCCGTCATCTACTCTACCATCTTTGCAGGCACACTCATCACAGCGCTAAGCTCGCACTGATTTTTTACCTGAGTAGGCCTAGAAATAAACATGCTAGCTTTTATTCCAGTTCTAACCAAAAAAATAAACCCTCGTTCCACAGAAGCTGCCATCAAGTATTTCCTCACGCAAGCAACCGCATCCATAATCCTTCTAATAGCTATCCTCTTCAACAATATACTCTCCGGACAATGAACCATAACCAATACTACCAATCAATACTCATCATTAATAATCATAATAGCTATAGCAATAAAACTAGGAATAGCCCCCTTTCACTTCTGAGTCCCAGAGGTTACCCAAGGCACCCCTCTGACATCCGGCCTGCTTCTTCTCACATGACAAAAACTAGCCCCCATCTCAATCATATACCAAATCTCTCCCTCACTAAACGTAAGCCTTCTCCTCACTCTCTCAATCTTATCCATCATAGCAGGCAGTTGAGGTGGATTAAACCAAACCCAGCTACGCAAAATCTTAGCATACTCCTCAATTACCCACATAGGATGAATAATAGCAGTTCTACCGTACAACCCTAACATAACCATTCTTAATTTAACTATTTATATTATCCTAACTACTACCGCATTCCTACTACTCAACTTAAACTCCAGCACCACGACCCTACTACTATCTCGCACCTGAAACAAGCTAACATGACTAACACCCTTAATTCCATCCACCCTCCTCTCCCTAGGAGGCCTGCCCCCGCTAACCGGCTTTTTGCCCAAATGGGCCATTATCGAAGAATTCACAAAAAACAATAGCCTCATCATCCCCACCATCATAGCCACCATCACCCTCCTTAACCTCTACTTCTACCTACGCCTAATCTACTCCACCTCAATCACACTACTCCCCATATCTAACAACGTAAAAATAAAATGACAGTTTGAACATACAAAACCCACCCCATTCCTCCCCACACTCATCGCCCTTACCACGCTACTCCTACCTATCTCCCCTTTTATACTAATAATCTTAT"),
	"163",
	"146",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES (
	"4535",
	"MT-ND1",
	"mitochondrially encoded NADH dehydrogenase 1",
	"P03886",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (3307..4262)",
	"956 bp",
	"protein coding",
	concat(">NC_012920.1:3307-4262 Homo sapiens mitochondrion, complete genome
		","ATACCCATGGCCAACCTCCTACTCCTCATTGTACCCATTCTAATCGCAATGGCATTCCTAATGCTTACCGAACGAAAAATTCTAGGCTATATACAACTACGCAAAGGCCCCAACGTTGTAGGCCCCTACGGGCTACTACAACCCTTCGCTGACGCCATAAAACTCTTCACCAAAGAGCCCCTAAAACCCGCCACATCTACCATCACCCTCTACATCACCGCCCCGACCTTAGCTCTCACCATCGCTCTTCTACTATGAACCCCCCTCCCCATACCCAACCCCCTGGTCAACCTCAACCTAGGCCTCCTATTTATTCTAGCCACCTCTAGCCTAGCCGTTTACTCAATCCTCTGATCAGGGTGAGCATCAAACTCAAACTACGCCCTGATCGGCGCACTGCGAGCAGTAGCCCAAACAATCTCATATGAAGTCACCCTAGCCATCATTCTACTATCAACATTACTAATAAGTGGCTCCTTTAACCTCTCCACCCTTATCACAACACAAGAACACCTCTGATTACTCCTGCCATCATGACCCTTGGCCATAATATGATTTATCTCCACACTAGCAGAGACCAACCGAACCCCCTTCGACCTTGCCGAAGGGGAGTCCGAACTAGTCTCAGGCTTCAACATCGAATACGCCGCAGGCCCCTTCGCCCTATTCTTCATAGCCGAATACACAAACATTATTATAATAAACACCCTCACCACTACAATCTTCCTAGGAACAACATATGACGCACTCTCCCCTGAACTCTACACAACATATTTTGTCACCAAGACCCTACTTCTAACCTCCCTGTTCTTATGAATTCGAACAGCATACCCCCGATTCCGCTACGACCAACTCATACACCTCCTATGAAAAAACTTCCTACCACTCACCCTAGCATTACTTATATGATATGTCTCCATACCCATTACAATCTCCAGCATTCCCCCTCAAACCTA"),
	"165",
	"129",
	"Leigh Syndrome"
);

INSERT INTO genes VALUES(
	"4540",
	"MT-ND5",
	"mitochondrially encoded NADH dehydrogenase 5",
	"P03915",
	"Homo sapiens (human)",
	"20-Apr-2021",
	"NC_012920.1 (12337..14148)",
	"1812 bp",
	"protein coding",
	concat(">NC_012920.1:12337-14148 Homo sapiens mitochondrion, complete genome
		","ATAACCATGCACACTACTATAACCACCCTAACCCTGACTTCCCTAATTCCCCCCATCCTTACCACCCTCGTTAACCCTAACAAAAAAAACTCATACCCCCATTATGTAAAATCCATTGTCGCATCCACCTTTATTATCAGTCTCTTCCCCACAACAATATTCATGTGCCTAGACCAAGAAGTTATTATCTCGAACTGACACTGAGCCACAACCCAAACAACCCAGCTCTCCCTAAGCTTCAAACTAGACTACTTCTCCATAATATTCATCCCTGTAGCATTGTTCGTTACATGGTCCATCATAGAATTCTCACTGTGATATATAAACTCAGACCCAAACATTAATCAGTTCTTCAAATATCTACTCATCTTCCTAATTACCATACTAATCTTAGTTACCGCTAACAACCTATTCCAACTGTTCATCGGCTGAGAGGGCGTAGGAATTATATCCTTCTTGCTCATCAGTTGATGATACGCCCGAGCAGATGCCAACACAGCAGCCATTCAAGCAATCCTATACAACCGTATCGGCGATATCGGTTTCATCCTCGCCTTAGCATGATTTATCCTACACTCCAACTCATGAGACCCACAACAAATAGCCCTTCTAAACGCTAATCCAAGCCTCACCCCACTACTAGGCCTCCTCCTAGCAGCAGCAGGCAAATCAGCCCAATTAGGTCTCCACCCCTGACTCCCCTCAGCCATAGAAGGCCCCACCCCAGTCTCAGCCCTACTCCACTCAAGCACTATAGTTGTAGCAGGAATCTTCTTACTCATCCGCTTCCACCCCCTAGCAGAAAATAGCCCACTAATCCAAACTCTAACACTATGCTTAGGCGCTATCACCACTCTGTTCGCAGCAGTCTGCGCCCTTACACAAAATGACATCAAAAAAATCGTAGCCTTCTCCACTTCAAGTCAACTAGGACTCATAATAGTTACAATCGGCATCAACCAACCACACCTAGCATTCCTGCACATCTGTACCCACGCCTTCTTCAAAGCCATACTATTTATGTGCTCCGGGTCCATCATCCACAACCTTAACAATGAACAAGATATTCGAAAAATAGGAGGACTACTCAAAACCATACCTCTCACTTCAACCTCCCTCACCATTGGCAGCCTAGCATTAGCAGGAATACCTTTCCTCACAGGTTTCTACTCCAAAGACCACATCATCGAAACCGCAAACATATCATACACAAACGCCTGAGCCCTATCTATTACTCTCATCGCTACCTCCCTGACAAGCGCCTATAGCACTCGAATAATTCTTCTCACCCTAACAGGTCAACCTCGCTTCCCCACCCTTACTAACATTAACGAAAATAACCCCACCCTACTAAACCCCATTAAACGCCTGGCAGCCGGAAGCCTATTCGCAGGATTTCTCATTACTAACAACATTTCCCCCGCATCCCCCTTCCAAACAACAATCCCCCTCTACCTAAAACTCACAGCCCTCGCTGTCACTTTCCTAGGACTTCTAACAGCCCTAGACCTCAACTACCTAACCAACAAACTTAAAATAAAATCCCCACTATGCACATTTTATTTCTCCAACATACTCGGATTCTACCCTAGCATCACACACCGCACAATCCCCTATCTAGGCCTTCTTACGAGCCAAAACCTGCCCCTACTCCTCCTAGACCTAACCTGACTAGAAAAGCTATTACCTAAAACAATTTCACAGCACCAAATCTCCACCTCCATCATCACCTCAACCCAAAAAGGCATAATTAAACTTTACTTCCTCTCTTTCTTCTTCCCACTCATCCTAACCCTACTCCTAATCACATAA"),
	"281",
	"252",
	"Leigh Syndrome"
);

-- Beginning of insertion of protein values

INSERT INTO proteins VALUES (
	"P00156",
	"Cytochrome b",
	"MT-CYB",
	"Homo sapiens (Human)",
	"3-Oct-2012",
	"integral component of mitochondrial inner membrane, mitochondrial inner membrane, mitochondrial respiratory chain complex III",
	"380 aa",
	concat('MTPMRKTNPL', 'MKLINHSFID', 'LPTPSNISAW',
		'WNFGSLLGAC', 'LILQITTGLF', 'LAMHYSPDAS',
		'TAFSSIAHIT', 'RDVNYGWIIR', 'YLHANGASMF',
		'FICLFLHIGR', 'GLYYGSFLYS', 'ETWNIGIILL',
		'LATMATAFMG', 'YVLPWGQMSF', 'WGATVITNLL',
		'SAIPYIGTDL', 'VQWIWGGYSV', 'DSPTLTRFFT',
		'FHFILPFIIA', 'ALATLHLLFL', 'HETGSNNPLG',
		'ITSHSDKITF', 'HPYYTIKDAL', 'GLLLFLLSLM',
		'TLTLFSPDLL', 'GDPDNYTLAN', 'PLNTPPHIKP',
		'EWYFLFAYTI', 'LRSVPNKLGG', 'VLALLLSILI',
		'LAMIPILHMS', 'KQQSMMFRPL', 'SQSLYWLLAA',
		'DLLILTWIGG', 'QPVSYPFTII', 'GQVASVLYFT',
		'TILILMPTIS', 'LIENKMLKWA')
);

INSERT INTO proteins VALUES (
	"P03923",
	"NADH-ubiquinone oxidoreductase chain 6",
	"MT-ND6",
	"Homo sapiens (Human)",
	"30-May-2000",
	"mitochondrial inner membrane",
	"174 aa",
	concat('MMYALFLLSV', 'GLVMGFVGFS', 'SKPSPIYGGL',
		'VLIVSGVVGC', 'VIILNFGGGY', 'MGLMVFLIYL', 
		'GGMMVVFGYT', 'TAMAIEEYPE', 'AWGSGVEVLV',
		'SVLVGLAMEV', 'GLVLWVKEYD', 'GVVVVVNFNS',
		'VGSWMIYEGE', 'GSGLIREDPI', 'GAGALYDYGR',
		'WLVVVTGWTL', 'FVGVYIVIEI', 'ARGN')
);

INSERT INTO proteins VALUES (
	"P03905",
	"NADH-ubiquinone oxidoreductase chain 4",
	"MT-ND4",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial respiratory chain complex I",
	"459 aa",
	concat("MLKLIVPTIMLLPLTWLSKKHMIWINTTTHSLIISIIPLLFFNQINNNLF",
	"SCSPTFSSDPLTTPLLMLTTWLLPLTIMASQRHLSSEPLSRKKLYLSMLI",
	"SLQISLIMTFTATELIMFYIFFETTLIPTLAIITRWGNQPERLNAGTYFL",
	"FYTLVGSLPLLIALIYTHNTLGSLNILLLTLTAQELSNSWANNLMWLAYT",
	"MAFMVKMPLYGLHLWLPKAHVEAPIAGSMVLAAVLLKLGGYGMMRLTLIL",
	"NPLTKHMAYPFLVLSLWGMIMTSSICLRQTDLKSLIAYSSISHMALVVTA",
	"ILIQTPWSFTGAVILMIAHGLTSSLLFCLANSNYERTHSRIMILSQGLQT",
	"LLPLMAFWWLLASLANLALPPTINLLGELSVLVTTFSWSNITLLLTGLNM",
	"LVTALYSLYMFTTTQWGSLTHHINNMKPSFTRENTLMFMHLSPILLLSLN",
	"PDIITGFSS")
);

INSERT INTO proteins VALUES (
	"P03901",
	"NADH-ubiquinone oxidoreductase chain 4L",
	"MT-ND4L",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial respiratory chain complex I",
	"98 aa",
	concat("MPLIYMNIMLAFTISLLGMLVYRSHLMSSLLCLEGMMLSLFIMATLMTLN",
		"THSLLANIVPIAMLVFAACEAAVGLALLVSISNTYGLDYVHNLNLLQC")
);

INSERT INTO proteins VALUES (
	"P03897",
	"NADH-ubiquinone oxidoreductase chain 3",
	"MT-ND3",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial respiratory chain complex I",
	"115 aa",
	concat("MNFALILMINTLLALLLMIITFWLPQLNGYMEKSTPYECGFDPMSPARVP",
		"FSMKFFLVAITFLLFDLEIALLLPLPWALQTTNLPLMVMSSLLLIIILAL",
		"SLAYEWLQKGLDWTE")
);

INSERT INTO proteins VALUES (
	"P00414",
	"Cytochrome c oxidase subunit 3",
	"MT-CO3",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrion",
	"261 aa",
	concat("MTHQSHAYHMVKPSPWPLTGALSALLMTSGLAMWFHFHSMTLLMLGLLTN",
		"TLTMYQWWRDVTRESTYQGHHTPPVQKGLRYGMILFITSEVFFFAGFFWA",
		"FYHSSLAPTPQLGGHWPPTGITPLNPLEVPLLNTSVLLASGVSITWAHHS",
		"LMENNRNQMIQALLITILLGLYFTLLQASEYFESPFTISDGIYGSTFFVA",
		"TGFHGLHVIIGSTFLTICFIRQLMFHFTSKHHFGFEAAAWYWHFVDVVWL",
		"FLYVSIYWWGS")
);

INSERT INTO proteins VALUES (
	"P00846",
	"ATP synthase subunit a",
	"MT-ATP6",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial proton-transporting ATP synthase complex",
	"226 aa",
	concat("MNENLFASFIAPTILGLPAAVLIILFPPLLIPTSKYLINNRLITTQQWLI",
	"KLTSKQMMTMHNTKGRTWSLMLVSLIIFIATTNLLGLLPHSFTPTTQLSM",
	"NLAMAIPLWAGTVIMGFRSKIKNALAHFLPQGTPTPLIPMLVIIETISLL",
	"IQPMALAVRLTANITAGHLLMHLIGSATLAMSTINLPSTLIIFTILILLT",
	"ILEIAVALIQAYVFTLLVSLYLHDNT")
);

INSERT INTO proteins VALUES (
	"P03928",
	"ATP synthase protein 8",
	"MT-ATP8",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial proton-transporting ATP synthase complex, mitochondrial proton-transporting ATP synthase complex, coupling factor F(o)",
	"68 aa",
	concat("MPQLNTTVWPTMITPMLLTLFLITQLKMLNTNYHLPPSPKPMKMKNYNKP",
		"WEPKWTKICSLHSLPPQS")
);

INSERT INTO proteins VALUES (
	"P00403",
	"Cytochrome c oxidase subunit 2",
	"MT-CO2",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrion",
	"227 aa",
	concat("MAHAAQVGLQDATSPIMEELITFHDHALMIIFLICFLVLYALFLTLTTKL",
	"TNTNISDAQEMETVWTILPAIILVLIALPSLRILYMTDEVNDPSLTIKSI",
	"GHQWYWTYEYTDYGGLIFNSYMLPPLFLEPGDLRLLDVDNRVVLPIEAPI",
	"RMMITSQDVLHSWAVPTLGLKTDAIPGRLNQTTFTATRPGVYYGQCSEIC",
	"GANHSFMPIVLELIPLKIFEMGPVFTL")
);

INSERT INTO proteins VALUES (
	"P00395",
	"Cytochrome c oxidase subunit 1",
	"MT-CO1",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial respiratory chain complex III, mitochondrial respiratory chain complex IV",
	"513 aa",
	concat("MFADRWLFSTNHKDIGTLYLLFGAWAGVLGTALSLLIRAELGQPGNLLGN",
	"DHIYNVIVTAHAFVMIFFMVMPIMIGGFGNWLVPLMIGAPDMAFPRMNNM",
	"SFWLLPPSLLLLLASAMVEAGAGTGWTVYPPLAGNYSHPGASVDLTIFSL",
	"HLAGVSSILGAINFITTIINMKPPAMTQYQTPLFVWSVLITAVLLLLSLP",
	"VLAAGITMLLTDRNLNTTFFDPAGGGDPILYQHLFWFFGHPEVYILILPG",
	"FGMISHIVTYYSGKKEPFGYMGMVWAMMSIGFLGFIVWAHHMFTVGMDVD",
	"TRAYFTSATMIIAIPTGVKVFSWLATLHGSNMKWSAAVLWALGFIFLFTV",
	"GGLTGIVLANSSLDIVLHDTYYVVAHFHYVLSMGAVFAIMGGFIHWFPLF",
	"SGYTLDQTYAKIHFTIMFIGVNLTFFPQHFLGLSGMPRRYSDYPDAYTTW",
	"NILSSVGSFISLTAVMLMIFMIWEAFASKRKVLMVEEPSMNLEWLYGCPP",
	"PYHTFEEPVYMKS")
);

INSERT INTO proteins VALUES (
	"P03891",
	"NADH-ubiquinone oxidoreductase chain 2",
	"MT-ND2",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial respiratory chain complex I",
	"347 aa",
	concat("MNPLAQPVIYSTIFAGTLITALSSHWFFTWVGLEMNMLAFIPVLTKKMNP",
	"RSTEAAIKYFLTQATASMILLMAILFNNMLSGQWTMTNTTNQYSSLMIMM",
	"AMAMKLGMAPFHFWVPEVTQGTPLTSGLLLLTWQKLAPISIMYQISPSLN",
	"VSLLLTLSILSIMAGSWGGLNQTQLRKILAYSSITHMGWMMAVLPYNPNM",
	"TILNLTIYIILTTTAFLLLNLNSSTTTLLLSRTWNKLTWLTPLIPSTLLS",
	"LGGLPPLTGFLPKWAIIEEFTKNNSLIIPTIMATITLLNLYFYLRLIYST",
	"SITLLPMSNNVKMKWQFEHTKPTPFLPTLIALTTLLLPISPFMLMIL")
);

INSERT INTO proteins VALUES (
	"P03886",
	"NADH-ubiquinone oxidoreductase chain 1",
	"MT-ND1",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial membrane, mitochondrial respiratory chain complex I",
	"318 aa",
	concat("MPMANLLLLIVPILIAMAFLMLTERKILGYMQLRKGPNVVGPYGLLQPFA",
	"DAMKLFTKEPLKPATSTITLYITAPTLALTIALLLWTPLPMPNPLVNLNL",
	"GLLFILATSSLAVYSILWSGWASNSNYALIGALRAVAQTISYEVTLAIIL",
	"LSTLLMSGSFNLSTLITTQEHLWLLLPSWPLAMMWFISTLAETNRTPFDL",
	"AEGESELVSGFNIEYAAGPFALFFMAEYTNIIMMNTLTTTIFLGTTYDAL",
	"SPELYTTYFVTKTLLLTSLFLWIRTAYPRFRYDQLMHLLWKNFLPLTLAL",
	"LMWYVSMPITISSIPPQT")
);

INSERT INTO proteins VALUES(
	"P03915",
	"NADH-ubiquinone oxidoreductase chain 5",
	"MT-ND5",
	"Homo sapiens (Human)",
	"7-Apr-2021",
	"mitochondrial inner membrane, mitochondrial respiratory chain complex I",
	"603 aa",
	concat("MTMHTTMTTLTLTSLIPPILTTLVNPNKKNSYPHYVKSIVASTFIISLFP",
	"TTMFMCLDQEVIISNWHWATTQTTQLSLSFKLDYFSMMFIPVALFVTWSI",
	"MEFSLWYMNSDPNINQFFKYLLIFLITMLILVTANNLFQLFIGWEGVGIM",
	"SFLLISWWYARADANTAAIQAILYNRIGDIGFILALAWFILHSNSWDPQQ",
	"MALLNANPSLTPLLGLLLAAAGKSAQLGLHPWLPSAMEGPTPVSALLHSS",
	"TMVVAGIFLLIRFHPLAENSPLIQTLTLCLGAITTLFAAVCALTQNDIKK",
	"IVAFSTSSQLGLMMVTIGINQPHLAFLHICTHAFFKAMLFMCSGSIIHNL",
	"NNEQDIRKMGGLLKTMPLTSTSLTIGSLALAGMPFLTGFYSKDHIIETAN",
	"MSYTNAWALSITLIATSLTSAYSTRMILLTLTGQPRFPTLTNINENNPTL",
	"LNPIKRLAAGSLFAGFLITNNISPASPFQTTIPLYLKLTALAVTFLGLLT",
	"ALDLNYLTNKLKMKSPLCTFYFSNMLGFYPSITHRTIPYLGLLTSQNLPL",
	"LLLDLTWLEKLLPKTISQHQISTSIITSTQKGMIKLYFLSFFFPLILTLL",
	"LIT")
);
